version: '3.4'

services:
  devopsautomation:
    image: devopsautomation
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
    -  ".env"
    ports:
      - 8181:8181
